export const data = [
  {
    id: 1,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 2,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 3,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 4,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 5,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 6,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 7,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 8,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 9,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 10,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 11,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 12,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 13,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 14,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 15,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 16,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 17,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 18,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 19,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
  {
    id: 20,
    title: "Titulo",
    src: "https://picsum.photos/640/360",
    paragraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga laborum numquam harum itaque cum eum! Totam aliquam consequuntur quo sit.",
    url: "#",
  },
]